### ISSUE TITLE
やることリスト

### ISSUE THREAD

**Issue by takatoshiono** [takatoshiono/dotfiles#4]
- [x] Brewfile（新しい Mac をセットアップする時に楽したい）
  - homebrew 本体でサポートしなくなるらしいので brewdler っていうの使えばいいのかなあ #9 
  - シェルスクリプトにして`brew install xxx`とかずらーって書いていけばいいのかな
- [x] ctrl-p or unite（あいまい検索したい）
- [x] vim-powerline（かっこいいらしい）
  - [x] lightline の方がいいかも？
- [ ] rails.vim （どんなものか知らない）
  - よくわからないからいらないかもしんまい
- [x] neocomplcache の設定を見直す
- [ ] Vim を homebrew のやつにする（Brefile にしたら管理が楽そうなイメージ）
  - `brew install macvim --override-system-vim`
  - [EDITOR](https://github.com/b4winckler/macvim/wiki/FAQ#how-can-i-use-macvim-to-edit-git-commit-messages)
- [x] Vundle 管理じゃないプラグインを整理する（といか vim/ 以下を全部整理したい）
- [x] oh-my-zsh とはなにか
- [x] `cd $(ghq list -p | peco)`するスクリプトをどこかに...
  - zsh じゃなくて bash
- [ ] vim で `.un~` ができないようにする
- [x] homebrew-cask
- [ ] vimfiler
- [x] .gitconfig を管理する
- [ ] ~~vim-fugitive + lightline.vim~~ #11 
- [ ] ctags をいい感じにする（オプション、Vim との連携）
- [ ] Unite.vim で ignore case と サブディレクトリ内のファイル検索できるようにする
- [ ] .bashrc から source しているファイルたちをよしなにする
- [x] zsh にする
- [x] JavaScript の開発環境を整える
- [x] composer のパス設定する
- [x] screen から tmux に移行する
- [ ] TERM の設定を見直す
  - http://unix.stackexchange.com/questions/139082/zsh-set-term-screen-256color-in-tmux-but-xterm-256color-without-tmux
  - `screen-256color`だと ssh 先のホストによっては top や vi したときにエラーメッセージが出る
  - bashrc では ssh コマンドに alias 設定している
  - alias 設定してしまった https://github.com/takatoshiono/dotfiles/commit/4d18b94c8ee997ee312c7d94d4a4681822886e89
- [ ] Unite.vim のドキュメントを読んで設定を理解、精査する
  - https://github.com/Shougo/unite.vim/blob/master/doc/unite.txt

**Comment by takatoshiono** [comment]
Brewfile is deprecated の件

https://github.com/rcmdnk/homebrew-file を使うか、自前でやるのがよさそう

**Comment by nafu** [comment]
http://takatoshiono.hatenablog.com/entry/2014/09/15/002737
ブログより。
いいですね :+1:
